server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/notification_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest