server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-auth
          uri: ${USER_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/users/auth/**

        - id: user-service
          uri: ${USER_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/users/**

        - id: trip-service
          uri: ${TRIP_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/api/trips/**

        - id: user-service-docs
          uri: ${USER_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/user/v3/api-docs
          filters:
            - RewritePath=/user/(?<segment>.*), /${segment}

        - id: trip-service-docs
          uri: ${TRIP_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/trip/v3/api-docs
          filters:
            - RewritePath=/trip/(?<segment>.*), /${segment}

springdoc:
  swagger-ui:
    path: /swagger-ui
    urls:
      - name: user-service
        url: /user/v3/api-docs
      - name: trip-service
        url: /trip/v3/api-docs

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationMustBe256BitsLongForHS256AlgorithmToWorkProperly}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.taxi.api_gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,gateway