server:
  port: 8082

spring:
  application:
    name: trip-service

  profiles:
    active: stub

  datasource:
    url: jdbc:postgresql://localhost:5434/trip_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest

  data:
    redis:
      host: localhost
      port: 6379

tariff:
  price-per-km: 2.5