server:
  port: 8082

spring:
  application:
    name: trip-service

  profiles:
    active: prod

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/trip_db}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationMustBe256BitsLongForHS256AlgorithmToWorkProperly}

services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081}

ors:
  api-key: ${ORS_API_KEY:eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjE4NjdhMWY3MTI0NDQ0NGZhY2I5MjczYjZlZDY5M2I2IiwiaCI6Im11cm11cjY0In0=}
  geocode-url: https://api.openrouteservice.org/geocode/search
  directions-url: https://api.openrouteservice.org/v2/directions/driving-car
tariff:
  price-per-km: 50.0